title: "Project #MovingForward"
description: An open-source directory to highlight VCs committing to diverse, inclusive and harassment-free workplaces
show_downloads: true
google_analytics: UA-115087160-1
theme: jekyll-theme-cayman
