title: "Project #MovingForward"
description: Highlighting VCs committed to diverse, inclusive, and harassment-free workplaces
show_downloads: true
google_analytics: UA-115087160-1
theme: jekyll-theme-cayman
