title: "Project #MovingForward"
description: A resource wiki to highlight VCs shifting the diversity, inclusion, and anti-harassment paradigm
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
